### ISSUE TITLE
does it work on Mac?

### ISSUE THREAD

**Issue by deshearth** [ymarco/paper-mode#1]
Hi, I'd like to try out this package. Is it supposed to work on Mac? I got compilation error when I make it.
Not sure if this is helpful. The error message is "ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)"

**Comment by ymarco** [comment]
Yeah, linking errors I couldn't solved stopped the development. The only place I could get it to compile and *run* are with both Emacs and mupdf installed through Guix.
I couldn't figure it out with both them on Arch, even when it compiles it errors out (or segfaults) when loaded in Emacs due to unfound symbols.
Maybe I'll resume development on Guix, but if it's this convoluted do it on a normal linux distro it probably would be similar on Mac.

I should mention the project status in the readme...
